# Generated by Django 5.2.8 on 2025-11-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("killer", "0004_remove_killer_active"),
        ("police", "0004_alter_policeofficer_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_number", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Open"), (2, "Closed"), (3, "Cold Case")],
                        default=1,
                    ),
                ),
                ("date_opened", models.DateField()),
                ("date_closed", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "killer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="killer.killer",
                    ),
                ),
                (
                    "officers",
                    models.ManyToManyField(
                        related_name="cases", to="police.policeofficer"
                    ),
                ),
            ],
        ),
    ]
