# Generated by Django 5.2.8 on 2025-11-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PoliceOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("chief", "Chief"),
                            ("captain", "Captain"),
                            ("sergeant", "Sergeant"),
                            ("detective", "Detective"),
                            ("analyst", "Analyst"),
                            ("officer", "Officer"),
                            ("blood_spatter_analyst", "Blood Spatter Analyst"),
                        ],
                        default="officer",
                        max_length=50,
                    ),
                ),
                ("badge_number", models.CharField(max_length=20, unique=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="police/"),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
