# Generated by Django 5.2.8 on 2025-11-18 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policeofficer",
            name="active",
        ),
        migrations.AddField(
            model_name="policeofficer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 18, 20, 6, 0, 654183, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="policeofficer",
            name="department",
            field=models.IntegerField(
                choices=[(1, "Homicide"), (2, "Forensics"), (3, "Narcotics")],
                default=1,
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="policeofficer",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Active"),
                    (2, "On Leave"),
                    (3, "Suspended"),
                    (4, "Retired"),
                    (5, "Deceased"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="policeofficer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="policeofficer",
            name="rank",
            field=models.IntegerField(
                choices=[
                    (1, "Chief"),
                    (2, "Captain"),
                    (3, "Sergeant"),
                    (4, "Detective"),
                    (5, "Analyst"),
                    (6, "Officer"),
                    (7, "Blood Spatter Analyst"),
                ],
                default=6,
                verbose_name="Rank",
            ),
        ),
    ]
