# Generated by Django 5.2.8 on 2025-11-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "police",
            "0002_remove_policeofficer_active_policeofficer_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="policeofficer",
            name="department",
            field=models.IntegerField(
                choices=[(1, "Homicide"), (2, "Forensics"), (3, "Narcotics")],
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="policeofficer",
            name="rank",
            field=models.IntegerField(
                choices=[
                    (1, "Chief"),
                    (2, "Captain"),
                    (3, "Sergeant"),
                    (4, "Detective"),
                    (5, "Analyst"),
                    (6, "Officer"),
                    (7, "Blood Spatter Analyst"),
                ],
                verbose_name="Rank",
            ),
        ),
        migrations.AlterField(
            model_name="policeofficer",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Active"),
                    (2, "On Leave"),
                    (3, "Suspended"),
                    (4, "Retired"),
                    (5, "Deceased"),
                ],
                verbose_name="Status",
            ),
        ),
    ]
