# Generated by Django 5.2.8 on 2025-11-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police", "0003_alter_policeofficer_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policeofficer",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="police/photo"),
        ),
    ]
