# Generated by Django 5.2.8 on 2025-11-20 20:37

import killer.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("killer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="killerphoto",
            name="image",
            field=models.ImageField(upload_to=killer.utils.killer_photo_path),
        ),
    ]
