# Generated by Django 5.2.8 on 2025-11-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("killer", "0002_alter_killerphoto_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="killer",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Dead"), (2, "Captured"), (3, "Missing"), (4, "Active")],
                default=4,
            ),
        ),
    ]
