# Generated by Django 5.2.8 on 2025-11-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("killer", "0003_killer_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="killer",
            name="active",
        ),
    ]
